import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/Header/NavBar";
import Footer from "./Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-0 m-0 gYisCF relative box-border bg-black-bg text-white-text font-sans">
      <NavBar/>  
       {children}
      <Footer/> 
       </body>
    </html>
  );
}
